version: "3.6"
services:
    rabbitmq:
        container_name: rabbitmq
        ports:
            - 5672:5672
            - 15672:15672
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest        
        image: rabbitmq:3-management
                
    ticketing:
        container_name: ticketingapi
        build: 
            context: .
            dockerfile: ./Ticketing.Microservice/Dockerfile
        ports:
            - 5000:5000
            - 5001:5001
        restart: on-failure        
        depends_on:
            - rabbitmq
        links: 
            - rabbitmq
        
    ticketconsumer:
        container_name: consumer
        build:
            context: .
            dockerfile: ./TicketProcessor.Microservice/Dockerfile
        ports:
            - 6001:6001
            - 6000:6000
        restart: on-failure
        depends_on:
            - rabbitmq  
        links: 
            - rabbitmq